// Gerado por scripts/xlsx_para_js.py — somente os campos: SUPERVISOR, GERENTE, FUNÇÃO, MUNICIPIO, DT_NASC, LOJA, COLABORADOR, ADMISSÃO.
window.COLABORADORES_DADOS = [
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-01",
  "LOJA": 5,
  "COLABORADOR": "JOSIMEIRE C.",
  "ADMISSÃO": "2024-04-02"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-02",
  "LOJA": 5,
  "COLABORADOR": "KAIC D.",
  "ADMISSÃO": "2025-02-11"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-03",
  "LOJA": 5,
  "COLABORADOR": "KAIQUE P.",
  "ADMISSÃO": "2026-01-26"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-04",
  "LOJA": 5,
  "COLABORADOR": "ANDREA D.",
  "ADMISSÃO": "2026-07-20"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-05",
  "LOJA": 5,
  "COLABORADOR": "KARINE T.",
  "ADMISSÃO": "2026-07-20"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-06",
  "LOJA": 5,
  "COLABORADOR": "RHAIZA R.",
  "ADMISSÃO": "2025-09-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-07",
  "LOJA": 5,
  "COLABORADOR": "TAMIRES C.",
  "ADMISSÃO": "2020-06-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BRUNO",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "CAC",
  "DT_NASC": "1999-01-08",
  "LOJA": 5,
  "COLABORADOR": "BRUNO D.",
  "ADMISSÃO": "2024-01-02"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-09",
  "LOJA": 7,
  "COLABORADOR": "ALESSANDRA S.",
  "ADMISSÃO": "2022-09-21"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-10",
  "LOJA": 7,
  "COLABORADOR": "DANILLE F.",
  "ADMISSÃO": "2021-05-10"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-11",
  "LOJA": 7,
  "COLABORADOR": "JAMILE D.",
  "ADMISSÃO": "2022-02-08"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-12",
  "LOJA": 7,
  "COLABORADOR": "OSMAR D.",
  "ADMISSÃO": "2024-09-02"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-13",
  "LOJA": 7,
  "COLABORADOR": "MARINA S.",
  "ADMISSÃO": "2022-08-09"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-14",
  "LOJA": 7,
  "COLABORADOR": "TAILAN D.",
  "ADMISSÃO": "2022-12-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-15",
  "LOJA": 7,
  "COLABORADOR": "LUZIANE T.",
  "ADMISSÃO": "2019-12-05"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "GENIVAL",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "CRUZ",
  "DT_NASC": "1999-01-16",
  "LOJA": 7,
  "COLABORADOR": "GENIVAL S.",
  "ADMISSÃO": "2020-06-01"
 },
 {
  "SUPERVISOR": "MICHELLE",
  "GERENTE": "MAICON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "EUC",
  "DT_NASC": "1999-01-17",
  "LOJA": 32,
  "COLABORADOR": "BLENDA M.",
  "ADMISSÃO": "2026-09-28"
 },
 {
  "SUPERVISOR": "MICHELLE",
  "GERENTE": "MAICON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "EUC",
  "DT_NASC": "1999-01-18",
  "LOJA": 32,
  "COLABORADOR": "GIOVANNA D.",
  "ADMISSÃO": "2026-09-28"
 },
 {
  "SUPERVISOR": "MICHELLE",
  "GERENTE": "MAICON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "EUC",
  "DT_NASC": "1999-01-19",
  "LOJA": 32,
  "COLABORADOR": "PEDRO M.",
  "ADMISSÃO": "2026-09-28"
 },
 {
  "SUPERVISOR": "MICHELLE",
  "GERENTE": "MAICON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "EUC",
  "DT_NASC": "1999-01-20",
  "LOJA": 32,
  "COLABORADOR": "RENATA L.",
  "ADMISSÃO": "2026-09-28"
 },
 {
  "SUPERVISOR": "MICHELLE",
  "GERENTE": "MAICON",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "EUC",
  "DT_NASC": "1999-01-21",
  "LOJA": 32,
  "COLABORADOR": "DIEGO A.",
  "ADMISSÃO": "2026-09-28"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-22",
  "LOJA": 9,
  "COLABORADOR": "DANIEL Z.",
  "ADMISSÃO": "2025-04-07"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-23",
  "LOJA": 9,
  "COLABORADOR": "JAIARA P.",
  "ADMISSÃO": "2026-05-25"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-24",
  "LOJA": 9,
  "COLABORADOR": "JOSE F.",
  "ADMISSÃO": "2025-09-23"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-25",
  "LOJA": 9,
  "COLABORADOR": "JOSEAN C.",
  "ADMISSÃO": "2022-05-02"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-26",
  "LOJA": 9,
  "COLABORADOR": "KAIQUE M.",
  "ADMISSÃO": "2019-11-01"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-27",
  "LOJA": 9,
  "COLABORADOR": "LUCAS L.",
  "ADMISSÃO": "2022-03-04"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-28",
  "LOJA": 9,
  "COLABORADOR": "ROSIMARE M.",
  "ADMISSÃO": "2022-09-16"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-29",
  "LOJA": 9,
  "COLABORADOR": "ANDREIA A.",
  "ADMISSÃO": "2026-03-02"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-30",
  "LOJA": 9,
  "COLABORADOR": "ANDREY D.",
  "ADMISSÃO": "2026-08-27"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-01-31",
  "LOJA": 9,
  "COLABORADOR": "CAIQUE D.",
  "ADMISSÃO": "2024-06-05"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-01",
  "LOJA": 9,
  "COLABORADOR": "CARLOS H.",
  "ADMISSÃO": "2025-02-20"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-02",
  "LOJA": 9,
  "COLABORADOR": "DANIEL A.",
  "ADMISSÃO": "2025-05-02"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-03",
  "LOJA": 9,
  "COLABORADOR": "EMANUELE B.",
  "ADMISSÃO": "2026-03-02"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-04",
  "LOJA": 9,
  "COLABORADOR": "GABRIEL S.",
  "ADMISSÃO": "2025-10-02"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-05",
  "LOJA": 9,
  "COLABORADOR": "GARIBALDE S.",
  "ADMISSÃO": "2024-03-22"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-06",
  "LOJA": 9,
  "COLABORADOR": "GEANDERSON D.",
  "ADMISSÃO": "2026-07-27"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-07",
  "LOJA": 9,
  "COLABORADOR": "GEOVANE S.",
  "ADMISSÃO": "2025-04-28"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-08",
  "LOJA": 9,
  "COLABORADOR": "HELDER D.",
  "ADMISSÃO": "2023-08-01"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "AUXILIAR DE LOGISTICA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-09",
  "LOJA": 9,
  "COLABORADOR": "ISABELLA G.",
  "ADMISSÃO": "2026-02-02"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-10",
  "LOJA": 8,
  "COLABORADOR": "ADRIA D.",
  "ADMISSÃO": "2024-06-06"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-11",
  "LOJA": 13,
  "COLABORADOR": "ANA L.",
  "ADMISSÃO": "2024-12-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-12",
  "LOJA": 8,
  "COLABORADOR": "ANA P.",
  "ADMISSÃO": "2020-06-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-13",
  "LOJA": 3,
  "COLABORADOR": "ANA V.",
  "ADMISSÃO": "2025-02-17"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-14",
  "LOJA": 14,
  "COLABORADOR": "ARIANE G.",
  "ADMISSÃO": "2024-04-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-15",
  "LOJA": 8,
  "COLABORADOR": "BEATRIZ D.",
  "ADMISSÃO": "2025-03-10"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-16",
  "LOJA": 14,
  "COLABORADOR": "BRUNA S.",
  "ADMISSÃO": "2024-03-04"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-17",
  "LOJA": 26,
  "COLABORADOR": "CLAUDIANE C.",
  "ADMISSÃO": "2026-06-22"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-18",
  "LOJA": 11,
  "COLABORADOR": "DAIANE S.",
  "ADMISSÃO": "2022-01-03"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-19",
  "LOJA": 13,
  "COLABORADOR": "DANIEL C.",
  "ADMISSÃO": "2025-08-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-20",
  "LOJA": 11,
  "COLABORADOR": "DIONE K.",
  "ADMISSÃO": "2020-06-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-21",
  "LOJA": 1,
  "COLABORADOR": "EDILENE L.",
  "ADMISSÃO": "2018-09-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-22",
  "LOJA": 15,
  "COLABORADOR": "ELIANE T.",
  "ADMISSÃO": "2024-04-02"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-23",
  "LOJA": 11,
  "COLABORADOR": "ELIAS S.",
  "ADMISSÃO": "2026-04-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-24",
  "LOJA": 11,
  "COLABORADOR": "EMYLLI S.",
  "ADMISSÃO": "2024-03-15"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-25",
  "LOJA": 3,
  "COLABORADOR": "EUGENIO L.",
  "ADMISSÃO": "2025-02-06"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-26",
  "LOJA": 14,
  "COLABORADOR": "FABIO F.",
  "ADMISSÃO": "2026-05-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-27",
  "LOJA": 13,
  "COLABORADOR": "FLORENICE C.",
  "ADMISSÃO": "2022-07-12"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-02-28",
  "LOJA": 3,
  "COLABORADOR": "GEISA S.",
  "ADMISSÃO": "2024-11-11"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-01",
  "LOJA": 4,
  "COLABORADOR": "GISELE D.",
  "ADMISSÃO": "2026-06-12"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-02",
  "LOJA": 3,
  "COLABORADOR": "HANNHA T.",
  "ADMISSÃO": "2025-08-23"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-03",
  "LOJA": 15,
  "COLABORADOR": "ICARO P.",
  "ADMISSÃO": "2024-04-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-04",
  "LOJA": 8,
  "COLABORADOR": "JACIARA A.",
  "ADMISSÃO": "2020-09-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-05",
  "LOJA": 13,
  "COLABORADOR": "JANINE S.",
  "ADMISSÃO": "2026-03-03"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-06",
  "LOJA": 6,
  "COLABORADOR": "JEFERSON S.",
  "ADMISSÃO": "2023-06-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-07",
  "LOJA": 4,
  "COLABORADOR": "JESSICA N.",
  "ADMISSÃO": "2026-08-29"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-08",
  "LOJA": 15,
  "COLABORADOR": "JOABES D.",
  "ADMISSÃO": "2023-02-22"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-09",
  "LOJA": 14,
  "COLABORADOR": "JOÃO V.",
  "ADMISSÃO": "2026-02-11"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-10",
  "LOJA": 2,
  "COLABORADOR": "JOSE R.",
  "ADMISSÃO": "2019-02-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-11",
  "LOJA": 15,
  "COLABORADOR": "JOYCE L.",
  "ADMISSÃO": "2025-03-10"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-12",
  "LOJA": 3,
  "COLABORADOR": "JÚLIA V.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-13",
  "LOJA": 15,
  "COLABORADOR": "LAINE O.",
  "ADMISSÃO": "2024-10-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-14",
  "LOJA": 26,
  "COLABORADOR": "LAIS F.",
  "ADMISSÃO": "2025-10-21"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-15",
  "LOJA": 3,
  "COLABORADOR": "LAISA K.",
  "ADMISSÃO": "2026-04-13"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-16",
  "LOJA": 11,
  "COLABORADOR": "LARISSA F.",
  "ADMISSÃO": "2024-08-09"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-17",
  "LOJA": 1,
  "COLABORADOR": "LEILA F.",
  "ADMISSÃO": "2023-07-13"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-18",
  "LOJA": 26,
  "COLABORADOR": "LILIAN D.",
  "ADMISSÃO": "2025-12-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-19",
  "LOJA": 2,
  "COLABORADOR": "LOURDES D.",
  "ADMISSÃO": "2020-06-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-20",
  "LOJA": 11,
  "COLABORADOR": "LUANA F.",
  "ADMISSÃO": "2024-09-04"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-21",
  "LOJA": 13,
  "COLABORADOR": "MARIELLE D.",
  "ADMISSÃO": "2026-01-07"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-22",
  "LOJA": 4,
  "COLABORADOR": "MIRLENE S.",
  "ADMISSÃO": "2021-04-20"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-23",
  "LOJA": 2,
  "COLABORADOR": "MONICA A.",
  "ADMISSÃO": "2025-05-26"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-24",
  "LOJA": 2,
  "COLABORADOR": "MONICA B.",
  "ADMISSÃO": "2022-01-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-25",
  "LOJA": 15,
  "COLABORADOR": "MONICA T.",
  "ADMISSÃO": "2025-04-11"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-26",
  "LOJA": 14,
  "COLABORADOR": "PAULA R.",
  "ADMISSÃO": "2026-01-12"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-27",
  "LOJA": 8,
  "COLABORADOR": "PAULO H.",
  "ADMISSÃO": "2023-12-13"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-28",
  "LOJA": 8,
  "COLABORADOR": "RIGELMA D.",
  "ADMISSÃO": "2021-12-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-29",
  "LOJA": 15,
  "COLABORADOR": "ROSICLEIDE P.",
  "ADMISSÃO": "2021-11-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-30",
  "LOJA": 8,
  "COLABORADOR": "SELMA P.",
  "ADMISSÃO": "2026-02-12"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-03-31",
  "LOJA": 1,
  "COLABORADOR": "SHELLDA B.",
  "ADMISSÃO": "2026-05-08"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-01",
  "LOJA": 1,
  "COLABORADOR": "SILVIA D.",
  "ADMISSÃO": "2023-04-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-02",
  "LOJA": 13,
  "COLABORADOR": "TAINA N.",
  "ADMISSÃO": "2026-03-25"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-03",
  "LOJA": 4,
  "COLABORADOR": "TATIANE D.",
  "ADMISSÃO": "2026-06-25"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-04",
  "LOJA": 2,
  "COLABORADOR": "VANESSA A.",
  "ADMISSÃO": "2022-06-02"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-05",
  "LOJA": 4,
  "COLABORADOR": "YASMIN M.",
  "ADMISSÃO": "2023-02-09"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-06",
  "LOJA": 4,
  "COLABORADOR": "ALLANNA B.",
  "ADMISSÃO": "2026-08-10"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-07",
  "LOJA": 13,
  "COLABORADOR": "AMANDA A.",
  "ADMISSÃO": "2026-06-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-08",
  "LOJA": 14,
  "COLABORADOR": "ARTHUR G.",
  "ADMISSÃO": "2026-07-21"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-09",
  "LOJA": 11,
  "COLABORADOR": "BARBARA S.",
  "ADMISSÃO": "2025-12-11"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-10",
  "LOJA": 14,
  "COLABORADOR": "BRUNA N.",
  "ADMISSÃO": "2026-05-21"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-11",
  "LOJA": 8,
  "COLABORADOR": "CAUA L.",
  "ADMISSÃO": "2025-10-27"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-12",
  "LOJA": 2,
  "COLABORADOR": "CLAUDIA B.",
  "ADMISSÃO": "2023-09-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-13",
  "LOJA": 3,
  "COLABORADOR": "DAVI R.",
  "ADMISSÃO": "2025-08-11"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-14",
  "LOJA": 26,
  "COLABORADOR": "DIJALMA D.",
  "ADMISSÃO": "2026-05-18"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-15",
  "LOJA": 14,
  "COLABORADOR": "DIRLEIDE S.",
  "ADMISSÃO": "2025-10-27"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-16",
  "LOJA": 2,
  "COLABORADOR": "ESTEFFANNE C.",
  "ADMISSÃO": "2024-03-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-17",
  "LOJA": 15,
  "COLABORADOR": "EVELLY S.",
  "ADMISSÃO": "2026-01-26"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-18",
  "LOJA": 4,
  "COLABORADOR": "ITALO H.",
  "ADMISSÃO": "2025-05-02"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-19",
  "LOJA": 1,
  "COLABORADOR": "IZAMARA B.",
  "ADMISSÃO": "2026-06-22"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-20",
  "LOJA": 26,
  "COLABORADOR": "JESSICA S.",
  "ADMISSÃO": "2026-06-22"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-21",
  "LOJA": 3,
  "COLABORADOR": "JOSE M.",
  "ADMISSÃO": "2026-03-21"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-22",
  "LOJA": 11,
  "COLABORADOR": "LAILSON S.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-23",
  "LOJA": 11,
  "COLABORADOR": "LETICIA D.",
  "ADMISSÃO": "2026-06-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-24",
  "LOJA": 8,
  "COLABORADOR": "LUANA V.",
  "ADMISSÃO": "2023-08-15"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-25",
  "LOJA": 15,
  "COLABORADOR": "LUDYMILLA S.",
  "ADMISSÃO": "2025-12-08"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-26",
  "LOJA": 3,
  "COLABORADOR": "MAIANE M.",
  "ADMISSÃO": "2026-06-17"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-27",
  "LOJA": 4,
  "COLABORADOR": "MAILANY I.",
  "ADMISSÃO": "2025-10-09"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-28",
  "LOJA": 11,
  "COLABORADOR": "MAINARA L.",
  "ADMISSÃO": "2024-09-02"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-29",
  "LOJA": 8,
  "COLABORADOR": "MARIA C.",
  "ADMISSÃO": "2026-02-03"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-04-30",
  "LOJA": 14,
  "COLABORADOR": "MILTON M.",
  "ADMISSÃO": "2026-08-24"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-01",
  "LOJA": 14,
  "COLABORADOR": "OTACILIA S.",
  "ADMISSÃO": "2025-08-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-02",
  "LOJA": 26,
  "COLABORADOR": "PATRICIA D.",
  "ADMISSÃO": "2025-06-04"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-03",
  "LOJA": 4,
  "COLABORADOR": "RAFAELA F.",
  "ADMISSÃO": "2025-05-10"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-04",
  "LOJA": 13,
  "COLABORADOR": "RAIMUNDA D.",
  "ADMISSÃO": "2025-11-17"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-05",
  "LOJA": 14,
  "COLABORADOR": "SAMANTA D.",
  "ADMISSÃO": "2026-07-21"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-06",
  "LOJA": 14,
  "COLABORADOR": "THALITA D.",
  "ADMISSÃO": "2024-11-05"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-07",
  "LOJA": 1,
  "COLABORADOR": "THAYNA S.",
  "ADMISSÃO": "2025-12-22"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-08",
  "LOJA": 11,
  "COLABORADOR": "YASMIN D.",
  "ADMISSÃO": "2024-11-05"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-09",
  "LOJA": 8,
  "COLABORADOR": "ANDRE L.",
  "ADMISSÃO": "2019-04-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-10",
  "LOJA": 1,
  "COLABORADOR": "ANDREA G.",
  "ADMISSÃO": "2022-01-03"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-11",
  "LOJA": 9,
  "COLABORADOR": "HYAGO D.",
  "ADMISSÃO": "2023-10-02"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-12",
  "LOJA": 8,
  "COLABORADOR": "IASNAYA D.",
  "ADMISSÃO": "2021-07-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-13",
  "LOJA": 1,
  "COLABORADOR": "KAROLINE C.",
  "ADMISSÃO": "2023-01-09"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-14",
  "LOJA": 9,
  "COLABORADOR": "MINEIA A.",
  "ADMISSÃO": "2022-07-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-15",
  "LOJA": 15,
  "COLABORADOR": "TAIALA D.",
  "ADMISSÃO": "2019-11-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "CAROL",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-16",
  "LOJA": 8,
  "COLABORADOR": "ANA C.",
  "ADMISSÃO": "2020-09-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "BIANCA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-17",
  "LOJA": 14,
  "COLABORADOR": "BIANCA V.",
  "ADMISSÃO": "2021-09-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "BIVANILDO",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-18",
  "LOJA": 15,
  "COLABORADOR": "ELINEIA T.",
  "ADMISSÃO": "2023-04-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "GABRIEL",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-19",
  "LOJA": 2,
  "COLABORADOR": "GABRIEL F.",
  "ADMISSÃO": "2021-06-14"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "HELDER",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-20",
  "LOJA": 3,
  "COLABORADOR": "HELDER P.",
  "ADMISSÃO": "2022-07-12"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "JULIANA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-21",
  "LOJA": 26,
  "COLABORADOR": "JULIANA C.",
  "ADMISSÃO": "2019-03-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "KEITH",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-22",
  "LOJA": 11,
  "COLABORADOR": "KEITH A.",
  "ADMISSÃO": "2022-01-03"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "RAYANE",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-23",
  "LOJA": 4,
  "COLABORADOR": "RAYANE R.",
  "ADMISSÃO": "2024-10-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "REINANE",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-24",
  "LOJA": 1,
  "COLABORADOR": "REINANE S.",
  "ADMISSÃO": "2023-04-01"
 },
 {
  "SUPERVISOR": "ALYSSON",
  "GERENTE": "TARCISIO",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-05-25",
  "LOJA": 13,
  "COLABORADOR": "TARCISIO B.",
  "ADMISSÃO": "2021-12-07"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-05-26",
  "LOJA": 28,
  "COLABORADOR": "ALCIENE D.",
  "ADMISSÃO": "2025-07-24"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-05-27",
  "LOJA": 28,
  "COLABORADOR": "CAIO L.",
  "ADMISSÃO": "2026-06-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-05-28",
  "LOJA": 28,
  "COLABORADOR": "ELIZANGELA S.",
  "ADMISSÃO": "2025-09-16"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-05-29",
  "LOJA": 28,
  "COLABORADOR": "EMILY G.",
  "ADMISSÃO": "2026-04-08"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-05-30",
  "LOJA": 28,
  "COLABORADOR": "REGIANE D.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-05-31",
  "LOJA": 28,
  "COLABORADOR": "RODRIGO F.",
  "ADMISSÃO": "2025-08-18"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-06-01",
  "LOJA": 28,
  "COLABORADOR": "JESSICA S.",
  "ADMISSÃO": "2025-08-18"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-06-02",
  "LOJA": 28,
  "COLABORADOR": "CHARLANE B.",
  "ADMISSÃO": "2025-11-04"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "A.CARLOS",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "JAC",
  "DT_NASC": "1999-06-03",
  "LOJA": 28,
  "COLABORADOR": "ANTONIO C.",
  "ADMISSÃO": "2025-07-24"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-04",
  "LOJA": 24,
  "COLABORADOR": "ANA L.",
  "ADMISSÃO": "2025-05-26"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-05",
  "LOJA": 24,
  "COLABORADOR": "DANIELE S.",
  "ADMISSÃO": "2024-03-18"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-06",
  "LOJA": 24,
  "COLABORADOR": "DANIELLE M.",
  "ADMISSÃO": "2024-03-05"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-07",
  "LOJA": 6,
  "COLABORADOR": "DIEGO O.",
  "ADMISSÃO": "2024-06-10"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-08",
  "LOJA": 6,
  "COLABORADOR": "EDILENE D.",
  "ADMISSÃO": "2021-02-12"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-09",
  "LOJA": 27,
  "COLABORADOR": "EDUARDO S.",
  "ADMISSÃO": "2026-01-07"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-10",
  "LOJA": 6,
  "COLABORADOR": "ERILANE N.",
  "ADMISSÃO": "2025-09-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-11",
  "LOJA": 6,
  "COLABORADOR": "IVANILDA P.",
  "ADMISSÃO": "2020-06-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-12",
  "LOJA": 6,
  "COLABORADOR": "JOSEFA G.",
  "ADMISSÃO": "2020-11-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-13",
  "LOJA": 27,
  "COLABORADOR": "LUZIANE D.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-14",
  "LOJA": 24,
  "COLABORADOR": "MARÍLIA D.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-15",
  "LOJA": 24,
  "COLABORADOR": "RAILDA D.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-16",
  "LOJA": 24,
  "COLABORADOR": "ROSIMEIRE D.",
  "ADMISSÃO": "2026-08-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-17",
  "LOJA": 24,
  "COLABORADOR": "BARBARA L.",
  "ADMISSÃO": "2026-02-11"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-18",
  "LOJA": 27,
  "COLABORADOR": "CAMILE D.",
  "ADMISSÃO": "2026-03-23"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-19",
  "LOJA": 6,
  "COLABORADOR": "KAMILY N.",
  "ADMISSÃO": "2026-01-08"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-20",
  "LOJA": 27,
  "COLABORADOR": "MARIA E.",
  "ADMISSÃO": "2025-09-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-21",
  "LOJA": 27,
  "COLABORADOR": "RAILANE D.",
  "ADMISSÃO": "2026-05-06"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-22",
  "LOJA": 6,
  "COLABORADOR": "RAISSA E.",
  "ADMISSÃO": "2025-04-16"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-23",
  "LOJA": 24,
  "COLABORADOR": "RYAN D.",
  "ADMISSÃO": "2024-11-14"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-24",
  "LOJA": 24,
  "COLABORADOR": "JAYNE S.",
  "ADMISSÃO": "2024-01-11"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-25",
  "LOJA": 27,
  "COLABORADOR": "JULIANE V.",
  "ADMISSÃO": "2025-05-13"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-26",
  "LOJA": 24,
  "COLABORADOR": "MANUELE S.",
  "ADMISSÃO": "2020-02-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "CARLOS",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-27",
  "LOJA": 24,
  "COLABORADOR": "CARLOS E.",
  "ADMISSÃO": "2023-08-15"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "PEDRO",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-28",
  "LOJA": 27,
  "COLABORADOR": "PEDRO D.",
  "ADMISSÃO": "2021-04-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "SÔNIA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SAJ",
  "DT_NASC": "1999-06-29",
  "LOJA": 6,
  "COLABORADOR": "SONIA D.",
  "ADMISSÃO": "2020-02-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": 0,
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-06-30",
  "LOJA": 17,
  "COLABORADOR": "SILVANA D.",
  "ADMISSÃO": "2026-06-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-01",
  "LOJA": 25,
  "COLABORADOR": "ADRIANA D.",
  "ADMISSÃO": "2023-01-16"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-02",
  "LOJA": 19,
  "COLABORADOR": "ADRIANA G.",
  "ADMISSÃO": "2023-05-09"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-03",
  "LOJA": 10,
  "COLABORADOR": "ALICE S.",
  "ADMISSÃO": "2024-12-23"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-04",
  "LOJA": 10,
  "COLABORADOR": "ALINE S.",
  "ADMISSÃO": "2023-02-03"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-05",
  "LOJA": 23,
  "COLABORADOR": "ANA C.",
  "ADMISSÃO": "2026-06-05"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-06",
  "LOJA": 21,
  "COLABORADOR": "ANA C.",
  "ADMISSÃO": "2024-09-02"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-07",
  "LOJA": 20,
  "COLABORADOR": "BARBARA S.",
  "ADMISSÃO": "2025-09-05"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-08",
  "LOJA": 21,
  "COLABORADOR": "BEATRIZ P.",
  "ADMISSÃO": "2025-03-24"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-09",
  "LOJA": 21,
  "COLABORADOR": "CAROLAINE B.",
  "ADMISSÃO": "2025-01-14"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-10",
  "LOJA": 10,
  "COLABORADOR": "CAROLINA S.",
  "ADMISSÃO": "2024-11-11"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-11",
  "LOJA": 18,
  "COLABORADOR": "CAROLINE D.",
  "ADMISSÃO": "2024-02-21"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-12",
  "LOJA": 10,
  "COLABORADOR": "CASSIA C.",
  "ADMISSÃO": "2022-09-15"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-13",
  "LOJA": 19,
  "COLABORADOR": "CINTIA C.",
  "ADMISSÃO": "2024-08-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-14",
  "LOJA": 10,
  "COLABORADOR": "CLEITON C.",
  "ADMISSÃO": "2022-09-09"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ROBSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-15",
  "LOJA": 31,
  "COLABORADOR": "CRISTIANE D.",
  "ADMISSÃO": "2026-04-15"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-16",
  "LOJA": 12,
  "COLABORADOR": "DAIANE S.",
  "ADMISSÃO": "2025-09-22"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-17",
  "LOJA": 30,
  "COLABORADOR": "DAINARA D.",
  "ADMISSÃO": "2025-05-20"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-18",
  "LOJA": 22,
  "COLABORADOR": "DAYANE L.",
  "ADMISSÃO": "2025-06-11"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-19",
  "LOJA": 12,
  "COLABORADOR": "DENISE F.",
  "ADMISSÃO": "2026-02-22"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-20",
  "LOJA": 30,
  "COLABORADOR": "ELOANE S.",
  "ADMISSÃO": "2025-04-09"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-21",
  "LOJA": 23,
  "COLABORADOR": "EVERALDO C.",
  "ADMISSÃO": "2024-05-15"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-22",
  "LOJA": 10,
  "COLABORADOR": "FABIANO G.",
  "ADMISSÃO": "2026-07-10"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-23",
  "LOJA": 23,
  "COLABORADOR": "FERNANDA A.",
  "ADMISSÃO": "2021-06-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-24",
  "LOJA": 17,
  "COLABORADOR": "FRANCISCO G.",
  "ADMISSÃO": "2026-02-02"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-25",
  "LOJA": 23,
  "COLABORADOR": "GEOVANE G.",
  "ADMISSÃO": "2023-11-20"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-26",
  "LOJA": 20,
  "COLABORADOR": "ISRAEL M.",
  "ADMISSÃO": "2024-10-04"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-27",
  "LOJA": 17,
  "COLABORADOR": "IVANILDES D.",
  "ADMISSÃO": "2024-08-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-28",
  "LOJA": 10,
  "COLABORADOR": "JANAI D.",
  "ADMISSÃO": "2026-04-13"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-29",
  "LOJA": 17,
  "COLABORADOR": "JANE P.",
  "ADMISSÃO": "2025-05-05"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-30",
  "LOJA": 12,
  "COLABORADOR": "JEANE D.",
  "ADMISSÃO": "2026-07-20"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-07-31",
  "LOJA": 25,
  "COLABORADOR": "JEFERSON S.",
  "ADMISSÃO": "2022-10-03"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-01",
  "LOJA": 12,
  "COLABORADOR": "JESSICA D.",
  "ADMISSÃO": "2022-02-11"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ROBSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-02",
  "LOJA": 31,
  "COLABORADOR": "JORGE A.",
  "ADMISSÃO": "2026-05-04"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-03",
  "LOJA": 18,
  "COLABORADOR": "JOTA Q.",
  "ADMISSÃO": "2025-07-07"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-04",
  "LOJA": 23,
  "COLABORADOR": "LIGIA B.",
  "ADMISSÃO": "2023-01-10"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-05",
  "LOJA": 21,
  "COLABORADOR": "LUCAS D.",
  "ADMISSÃO": "2023-07-15"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-06",
  "LOJA": 22,
  "COLABORADOR": "LUCAS L.",
  "ADMISSÃO": "2023-01-02"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-07",
  "LOJA": 22,
  "COLABORADOR": "LUCIANA M.",
  "ADMISSÃO": "2023-08-15"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-08",
  "LOJA": 25,
  "COLABORADOR": "LUIS F.",
  "ADMISSÃO": "2025-04-16"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-09",
  "LOJA": 21,
  "COLABORADOR": "MARCOS R.",
  "ADMISSÃO": "2025-05-26"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-10",
  "LOJA": 19,
  "COLABORADOR": "MARIANA R.",
  "ADMISSÃO": "2024-03-11"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-11",
  "LOJA": 10,
  "COLABORADOR": "MARIZETE C.",
  "ADMISSÃO": "2025-05-19"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-12",
  "LOJA": 20,
  "COLABORADOR": "MARTA C.",
  "ADMISSÃO": "2026-08-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-13",
  "LOJA": 17,
  "COLABORADOR": "MATHEUS S.",
  "ADMISSÃO": "2024-03-04"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-14",
  "LOJA": 19,
  "COLABORADOR": "MAYARA S.",
  "ADMISSÃO": "2022-09-16"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-15",
  "LOJA": 21,
  "COLABORADOR": "MICHELE Q.",
  "ADMISSÃO": "2022-09-13"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-16",
  "LOJA": 25,
  "COLABORADOR": "NAIARA L.",
  "ADMISSÃO": "2025-01-08"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-17",
  "LOJA": 25,
  "COLABORADOR": "NATIEL F.",
  "ADMISSÃO": "2023-11-10"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-18",
  "LOJA": 30,
  "COLABORADOR": "RAFAEL L.",
  "ADMISSÃO": "2022-10-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-19",
  "LOJA": 12,
  "COLABORADOR": "RAYANE C.",
  "ADMISSÃO": "2026-04-15"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-20",
  "LOJA": 19,
  "COLABORADOR": "REJANE D.",
  "ADMISSÃO": "2025-10-06"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-21",
  "LOJA": 18,
  "COLABORADOR": "ROSENI Q.",
  "ADMISSÃO": "2022-07-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-22",
  "LOJA": 19,
  "COLABORADOR": "ROSIANE L.",
  "ADMISSÃO": "2026-05-08"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-23",
  "LOJA": 23,
  "COLABORADOR": "SANDRO B.",
  "ADMISSÃO": "2022-11-04"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-24",
  "LOJA": 30,
  "COLABORADOR": "SUELEM D.",
  "ADMISSÃO": "2024-12-17"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-25",
  "LOJA": 25,
  "COLABORADOR": "TAINA C.",
  "ADMISSÃO": "2025-07-08"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-26",
  "LOJA": 18,
  "COLABORADOR": "TAIS L.",
  "ADMISSÃO": "2025-05-12"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-27",
  "LOJA": 23,
  "COLABORADOR": "THAIS B.",
  "ADMISSÃO": "2024-06-10"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-28",
  "LOJA": 23,
  "COLABORADOR": "TOMAZ A.",
  "ADMISSÃO": "2026-06-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-29",
  "LOJA": 12,
  "COLABORADOR": "VANDEVAL D.",
  "ADMISSÃO": "2025-06-16"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-30",
  "LOJA": 10,
  "COLABORADOR": "VERONICE V.",
  "ADMISSÃO": "2023-04-05"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-08-31",
  "LOJA": 21,
  "COLABORADOR": "ALICE B.",
  "ADMISSÃO": "2026-04-15"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-01",
  "LOJA": 25,
  "COLABORADOR": "ALISSON V.",
  "ADMISSÃO": "2026-07-06"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-02",
  "LOJA": 22,
  "COLABORADOR": "ANA F.",
  "ADMISSÃO": "2026-08-14"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-03",
  "LOJA": 21,
  "COLABORADOR": "ANDRESSA R.",
  "ADMISSÃO": "2026-08-26"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-04",
  "LOJA": 17,
  "COLABORADOR": "ANNA C.",
  "ADMISSÃO": "2026-08-03"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-05",
  "LOJA": 18,
  "COLABORADOR": "ANNE J.",
  "ADMISSÃO": "2025-04-23"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ROBSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-06",
  "LOJA": 31,
  "COLABORADOR": "BIANCA D.",
  "ADMISSÃO": "2025-07-21"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-07",
  "LOJA": 23,
  "COLABORADOR": "BRUNA S.",
  "ADMISSÃO": "2026-09-10"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-08",
  "LOJA": 22,
  "COLABORADOR": "CAIQUE M.",
  "ADMISSÃO": "2025-10-22"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-09",
  "LOJA": 22,
  "COLABORADOR": "CARLOS A.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-10",
  "LOJA": 12,
  "COLABORADOR": "DAYSE A.",
  "ADMISSÃO": "2026-03-05"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-11",
  "LOJA": 10,
  "COLABORADOR": "DÉBORA S.",
  "ADMISSÃO": "2026-08-18"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-12",
  "LOJA": 10,
  "COLABORADOR": "DJALMA D.",
  "ADMISSÃO": "2026-04-16"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-13",
  "LOJA": 25,
  "COLABORADOR": "EDGAR R.",
  "ADMISSÃO": "2026-02-04"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-14",
  "LOJA": 23,
  "COLABORADOR": "ELIANA D.",
  "ADMISSÃO": "2026-04-13"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-15",
  "LOJA": 17,
  "COLABORADOR": "FELIPE G.",
  "ADMISSÃO": "2025-02-17"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-16",
  "LOJA": 17,
  "COLABORADOR": "FERNANDA B.",
  "ADMISSÃO": "2025-10-13"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-17",
  "LOJA": 19,
  "COLABORADOR": "FRANCIELE M.",
  "ADMISSÃO": "2025-07-08"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-18",
  "LOJA": 25,
  "COLABORADOR": "GEOVANA B.",
  "ADMISSÃO": "2026-02-11"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-19",
  "LOJA": 23,
  "COLABORADOR": "GRESIELE D.",
  "ADMISSÃO": "2026-05-07"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-20",
  "LOJA": 21,
  "COLABORADOR": "HERBERT P.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-21",
  "LOJA": 23,
  "COLABORADOR": "IARA N.",
  "ADMISSÃO": "2025-11-17"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-22",
  "LOJA": 10,
  "COLABORADOR": "JANIESTE T.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-23",
  "LOJA": 20,
  "COLABORADOR": "JESSICA D.",
  "ADMISSÃO": "2026-09-03"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-24",
  "LOJA": 17,
  "COLABORADOR": "JOANE F.",
  "ADMISSÃO": "2026-09-11"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-25",
  "LOJA": 23,
  "COLABORADOR": "JOÃO V.",
  "ADMISSÃO": "2026-08-03"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-26",
  "LOJA": 10,
  "COLABORADOR": "JOSIANE C.",
  "ADMISSÃO": "2026-06-08"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-27",
  "LOJA": 10,
  "COLABORADOR": "KARINE B.",
  "ADMISSÃO": "2025-10-09"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-28",
  "LOJA": 22,
  "COLABORADOR": "KETHELEEN D.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-29",
  "LOJA": 22,
  "COLABORADOR": "KETLYN C.",
  "ADMISSÃO": "2025-01-14"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-09-30",
  "LOJA": 20,
  "COLABORADOR": "LILIANE P.",
  "ADMISSÃO": "2022-10-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-01",
  "LOJA": 18,
  "COLABORADOR": "LÍVIA D.",
  "ADMISSÃO": "2025-11-19"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-02",
  "LOJA": 30,
  "COLABORADOR": "LUCIANO S.",
  "ADMISSÃO": "2024-02-21"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-03",
  "LOJA": 30,
  "COLABORADOR": "MARCELO O.",
  "ADMISSÃO": "2025-10-20"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-04",
  "LOJA": 30,
  "COLABORADOR": "MARCOS P.",
  "ADMISSÃO": "2026-08-17"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ROBSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-05",
  "LOJA": 31,
  "COLABORADOR": "MARIA E.",
  "ADMISSÃO": "2026-08-03"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-06",
  "LOJA": 21,
  "COLABORADOR": "PABLO H.",
  "ADMISSÃO": "2026-05-18"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-07",
  "LOJA": 25,
  "COLABORADOR": "PAULA K.",
  "ADMISSÃO": "2025-10-11"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-08",
  "LOJA": 19,
  "COLABORADOR": "PAULA S.",
  "ADMISSÃO": "2024-12-02"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-09",
  "LOJA": 18,
  "COLABORADOR": "PEDRO P.",
  "ADMISSÃO": "2026-04-06"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-10",
  "LOJA": 17,
  "COLABORADOR": "RAIANE E.",
  "ADMISSÃO": "2026-04-07"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-11",
  "LOJA": 22,
  "COLABORADOR": "REBECA N.",
  "ADMISSÃO": "2026-04-18"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-12",
  "LOJA": 19,
  "COLABORADOR": "TAINÃ P.",
  "ADMISSÃO": "2026-02-11"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-13",
  "LOJA": 20,
  "COLABORADOR": "THAINA S.",
  "ADMISSÃO": "2026-09-14"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-14",
  "LOJA": 19,
  "COLABORADOR": "VANUZA S.",
  "ADMISSÃO": "2025-06-04"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-15",
  "LOJA": 12,
  "COLABORADOR": "VITORIA G.",
  "ADMISSÃO": "2025-09-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-16",
  "LOJA": 21,
  "COLABORADOR": "ANA P.",
  "ADMISSÃO": "2022-09-19"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-17",
  "LOJA": 12,
  "COLABORADOR": "BIANCA D.",
  "ADMISSÃO": "2025-08-18"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-18",
  "LOJA": 22,
  "COLABORADOR": "CRISTIANE S.",
  "ADMISSÃO": "2024-10-09"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-19",
  "LOJA": 23,
  "COLABORADOR": "DIEGO S.",
  "ADMISSÃO": "2025-07-14"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-20",
  "LOJA": 30,
  "COLABORADOR": "IARA D.",
  "ADMISSÃO": "2025-02-19"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-21",
  "LOJA": 20,
  "COLABORADOR": "MAGALI D.",
  "ADMISSÃO": "2023-11-20"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-22",
  "LOJA": 17,
  "COLABORADOR": "MAIANE S.",
  "ADMISSÃO": "2026-06-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-23",
  "LOJA": 25,
  "COLABORADOR": "MARIANA S.",
  "ADMISSÃO": "2023-04-01"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-24",
  "LOJA": 17,
  "COLABORADOR": "TATYANE S.",
  "ADMISSÃO": "2025-02-03"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ADRIANA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-25",
  "LOJA": 20,
  "COLABORADOR": "ADRIANA S.",
  "ADMISSÃO": "2024-04-01"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "DÉBORA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-26",
  "LOJA": 21,
  "COLABORADOR": "DEBORA G.",
  "ADMISSÃO": "2023-10-24"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "Gerente",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-27",
  "LOJA": 19,
  "COLABORADOR": "EDINAR F.",
  "ADMISSÃO": "2024-03-05"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "EMERSON",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-28",
  "LOJA": 23,
  "COLABORADOR": "EMERSON S.",
  "ADMISSÃO": "2025-08-18"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "ISMAELE",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-29",
  "LOJA": 30,
  "COLABORADOR": "ISMAELE J.",
  "ADMISSÃO": "2022-08-11"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JAMILLE",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-30",
  "LOJA": 25,
  "COLABORADOR": "JAMILE D.",
  "ADMISSÃO": "2024-05-02"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "JESSICA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-10-31",
  "LOJA": 10,
  "COLABORADOR": "JESSICA F.",
  "ADMISSÃO": "2022-09-10"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "MAILSON",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-11-01",
  "LOJA": 22,
  "COLABORADOR": "MAILSON D.",
  "ADMISSÃO": "2024-03-12"
 },
 {
  "SUPERVISOR": "RAFAEL",
  "GERENTE": "NADSON",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-11-02",
  "LOJA": 12,
  "COLABORADOR": "NADSON B.",
  "ADMISSÃO": "2026-09-24"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "NIVIA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-11-03",
  "LOJA": 19,
  "COLABORADOR": "NIVIA P.",
  "ADMISSÃO": "2024-09-02"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "RAYRA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-11-04",
  "LOJA": 18,
  "COLABORADOR": "RAYRA M.",
  "ADMISSÃO": "2022-07-06"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "ROBSON",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-11-05",
  "LOJA": 31,
  "COLABORADOR": "ROBSON C.",
  "ADMISSÃO": "2025-06-05"
 },
 {
  "SUPERVISOR": "MAICON",
  "GERENTE": "WESLLEY",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-11-06",
  "LOJA": 17,
  "COLABORADOR": "WESLLEY A.",
  "ADMISSÃO": "2025-05-15"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-07",
  "LOJA": 29,
  "COLABORADOR": "ADINAILDES D.",
  "ADMISSÃO": "2024-07-04"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-08",
  "LOJA": 16,
  "COLABORADOR": "ALANA S.",
  "ADMISSÃO": "2025-10-20"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-09",
  "LOJA": 29,
  "COLABORADOR": "ALBER S.",
  "ADMISSÃO": "2023-05-02"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-10",
  "LOJA": 16,
  "COLABORADOR": "FELIPE G.",
  "ADMISSÃO": "2025-11-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-11",
  "LOJA": 16,
  "COLABORADOR": "ITAMARA D.",
  "ADMISSÃO": "2024-04-02"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-12",
  "LOJA": 29,
  "COLABORADOR": "JAMILE B.",
  "ADMISSÃO": "2026-08-10"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-13",
  "LOJA": 29,
  "COLABORADOR": "JOAO V.",
  "ADMISSÃO": "2024-06-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-14",
  "LOJA": 29,
  "COLABORADOR": "JOSELILYAN D.",
  "ADMISSÃO": "2025-08-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-15",
  "LOJA": 16,
  "COLABORADOR": "MAYANA D.",
  "ADMISSÃO": "2025-10-10"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-16",
  "LOJA": 29,
  "COLABORADOR": "NATALE C.",
  "ADMISSÃO": "2025-02-11"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-17",
  "LOJA": 29,
  "COLABORADOR": "REIJANE S.",
  "ADMISSÃO": "2025-10-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-18",
  "LOJA": 29,
  "COLABORADOR": "SILVANA S.",
  "ADMISSÃO": "2022-04-06"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "BALCONISTA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-19",
  "LOJA": 16,
  "COLABORADOR": "TAMIRES S.",
  "ADMISSÃO": "2025-10-22"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-20",
  "LOJA": 16,
  "COLABORADOR": "CAROLINE S.",
  "ADMISSÃO": "2025-12-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-21",
  "LOJA": 29,
  "COLABORADOR": "DANIELE D.",
  "ADMISSÃO": "2025-10-27"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-22",
  "LOJA": 29,
  "COLABORADOR": "EMILI D.",
  "ADMISSÃO": "2026-06-22"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-23",
  "LOJA": 29,
  "COLABORADOR": "EMILLY B.",
  "ADMISSÃO": "2026-04-01"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-24",
  "LOJA": 29,
  "COLABORADOR": "GEOVANA D.",
  "ADMISSÃO": "2024-10-11"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-25",
  "LOJA": 16,
  "COLABORADOR": "JESSICA D.",
  "ADMISSÃO": "2026-05-08"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-26",
  "LOJA": 16,
  "COLABORADOR": "SAMANTA C.",
  "ADMISSÃO": "2026-05-08"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "CAIXA",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-27",
  "LOJA": 16,
  "COLABORADOR": "VALDIONE L.",
  "ADMISSÃO": "2023-05-16"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "FARMACEUTICO",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-28",
  "LOJA": 16,
  "COLABORADOR": "ADEMILTON H.",
  "ADMISSÃO": "2025-10-03"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "KLEBER",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-29",
  "LOJA": 29,
  "COLABORADOR": "ELANE D.",
  "ADMISSÃO": "2026-07-06"
 },
 {
  "SUPERVISOR": "MARCELLO",
  "GERENTE": "NARA",
  "FUNÇÃO": "GERENTE",
  "MUNICIPIO": "VAL",
  "DT_NASC": "1999-11-30",
  "LOJA": 16,
  "COLABORADOR": "UIONARA G.",
  "ADMISSÃO": "2022-06-01"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "ADMINISTRATIVO",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-12-01",
  "LOJA": 9,
  "COLABORADOR": "GUTEMBERG B.",
  "ADMISSÃO": "2025-11-03"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "SUPERVISOR",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-12-02",
  "LOJA": 9,
  "COLABORADOR": "ALYSSON C.",
  "ADMISSÃO": "2021-11-01"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "SUPERVISOR",
  "MUNICIPIO": "FSA",
  "DT_NASC": "1999-12-02",
  "LOJA": 9,
  "COLABORADOR": "MARCELLO J.",
  "ADMISSÃO": "2023-02-01"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "SUPERVISOR",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-12-02",
  "LOJA": 9,
  "COLABORADOR": "RAFAEL T.",
  "ADMISSÃO": "2021-08-16"
 },
 {
  "SUPERVISOR": "ISAAC",
  "GERENTE": "RAQUEL",
  "FUNÇÃO": "SUPERVISOR",
  "MUNICIPIO": "SSA",
  "DT_NASC": "1999-12-02",
  "LOJA": 9,
  "COLABORADOR": "MAICON C.",
  "ADMISSÃO": "2024-01-15"
 }
];
